/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApplicationLogo: typeof import('./Components/ApplicationLogo.vue')['default']
    Checkbox: typeof import('./Components/Checkbox.vue')['default']
    DangerButton: typeof import('./Components/DangerButton.vue')['default']
    Dropdown: typeof import('./Components/Dropdown.vue')['default']
    DropdownLink: typeof import('./Components/DropdownLink.vue')['default']
    InertiaHead: typeof import('@inertiajs/vue3')['Head']
    InertiaLink: typeof import('@inertiajs/vue3')['Link']
    InputError: typeof import('./Components/InputError.vue')['default']
    InputLabel: typeof import('./Components/InputLabel.vue')['default']
    Modal: typeof import('./Components/Modal.vue')['default']
    NavLink: typeof import('./Components/NavLink.vue')['default']
    PrimaryButton: typeof import('./Components/PrimaryButton.vue')['default']
    ResponsiveNavLink: typeof import('./Components/ResponsiveNavLink.vue')['default']
    SecondaryButton: typeof import('./Components/SecondaryButton.vue')['default']
    TextInput: typeof import('./Components/TextInput.vue')['default']
    UiLinkCom: typeof import('./Components/Ui/LinkCom.vue')['default']
    UiTestComponent: typeof import('./Components/Ui/TestComponent.vue')['default']
  }
}
